### ISSUE TITLE
socket.io.js not being served.

### ISSUE THREAD

**Issue by knpwrs** [phusion/passenger-nodejs-websocket-demo#3]
I have the following `nginx` configuration:

``` nginx
server {
  listen 80;
  root /home/kpowers/app/public;
  passenger_enabled on;
  passenger_app_type node;
  passenger_startup_file app.js;
}
```

The app starts and the root path is loaded but the client receives a 404 for `socket.io.js`:

![image](https://cloud.githubusercontent.com/assets/174864/10559628/57f9b12e-74c3-11e5-8edb-b1745ed4a928.png)

The following entry appears in the `nginx` error log:

``` log
[error] 1042#0: *5 open() "/home/kpowers/app/public/socket.io/socket.io.js" failed (2: No such file or directory)
```

The app works fine on its own when running without Passenger. My guess is that Passenger sees that the request is for a file and doesn't expect that the app is supposed to serve it. I checked the Passenger [Nginx Reference Docs](https://www.phusionpassenger.com/library/config/nginx/reference/) but didn't see anything (at first glance) about sending certain file requests through to the app.

Thoughts?

**Comment by FooBarWidget** [comment]
Passenger works as follows. If the file exists on the filesystem, then Passenger will make Nginx serve it directly. Otherwise, Passenger will forward the request to the app.

Are you running the passenger-nodejs-websocket-demo or are you running a different app?

The error message seems to indicate that Passenger isn't running, or that it's not active. Can you check that Passenger is running? Run `passenger-config list-instances` to check.

Do you see any other messages in the Nginx error log?

**Comment by knpwrs** [comment]
Must be user error. I just tried it on Ubuntu 14.04 x64 and it works. I don't remember which Ubuntu I was using before.
